import type { Rule, RuleMatch } from "./types.ts"

function matches(pattern: RegExp, text: string): RuleMatch[] {
  const copy = new RegExp(pattern.source, pattern.flags.includes("g") ? pattern.flags : `${pattern.flags}g`)
  const found: RuleMatch[] = []
  for (const match of text.matchAll(copy)) {
    if (match.index !== undefined && match[0]) found.push({ index: match.index, text: match[0] })
  }
  return found
}

function phrase(pattern: RegExp): NonNullable<Rule["detect"]> {
  return Object.assign((text: string) => matches(pattern, text), { expression: pattern.toString() })
}

export const RULES: readonly Rule[] = [
  { id: "fence-nolang", detection: "An opening code fence has an empty language/info label.", category: "structural", description: "A code fence has no language label.", severity: "MED", confidence: "certain", profiles: "all", action: "Choose a language label that matches the protected content without changing its bytes.", autofix: "review" },
  { id: "frontmatter-unclosed", detection: "An initial frontmatter delimiter has no matching closing delimiter.", category: "structural", description: "Opening YAML frontmatter has no closing delimiter.", severity: "MED", confidence: "likely", profiles: "all", action: "Close the frontmatter block or replace its opening delimiter.", autofix: "never" },
  { id: "fence-unclosed", detection: "A code fence has no later empty matching marker of at least its opening length.", category: "structural", description: "Opening code fence has no matching closing marker.", severity: "MED", confidence: "likely", profiles: "all", action: "Close the fence with its opening marker, or make the content ordinary Markdown.", autofix: "never" },
  { id: "heading-skip", detection: "Compare heading depths in document order; PR profiles permit an initial H2.", category: "structural", description: "A heading skips a hierarchy level.", severity: "MED", confidence: "likely", profiles: "all", action: "Use a heading level that follows the surrounding hierarchy.", autofix: "review" },
  { id: "heading-one", detection: "Count H1 headings outside protected regions for applicable profiles.", category: "structural", description: "A document has more than one level-one heading.", severity: "MED", confidence: "likely", profiles: ["generic", "readme", "adr", "runbook", "cutover", "spec", "design", "changelog", "incident", "api-reference", "migration", "security", "risk-assessment"], action: "Keep one document title, unless this file intentionally combines documents.", autofix: "review" },
  { id: "table-underfit", detection: "Inspect a recognized GFM table with fewer than two columns or no data rows.", category: "structural", description: "A GFM table has fewer than two columns or no data rows.", severity: "LOW", confidence: "contextual", profiles: "all", action: "Use a list for one-dimensional content or add the missing table dimension.", autofix: "review" },
  { id: "link-dead", detection: "Resolve literal local link destinations relative to the containing document and check existence.", category: "structural", description: "A literal local Markdown link target does not exist.", severity: "HIGH", confidence: "certain", profiles: "all", action: "Correct the local path or add the target file. Network URLs and anchors are not fetched.", autofix: "never" },
  { id: "section-missing", detection: "Compare parsed heading titles with the selected profile heading-alias groups.", category: "factualGap", description: "A profile-relevant section is absent.", severity: "MED", confidence: "contextual", profiles: ["pr", "readme", "adr", "runbook", "cutover", "spec", "design", "incident", "api-reference", "migration", "security", "risk-assessment"], action: "Confirm whether this document needs the named section, then add it only when the facts are available.", autofix: "never" },
  { id: "tell-notxbuty", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "A contrast construction may be rhetorical rather than specific.", severity: "LOW", confidence: "contextual", profiles: "all", action: "State the concrete distinction and its consequence.", autofix: "review", detect: phrase(/\b(?:is not|isn't|are not|aren't|not just|not only|it's not)\b[^.!?]{2,60}?\b(?:but|rather|it's|it is)\b/i) },
  { id: "tell-significance", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "An importance word may need a supporting consequence or be valid terminology.", severity: "LOW", confidence: "contextual", profiles: "all", action: "Name the affected behavior, decision, or measurable consequence.", autofix: "review", detect: phrase(/\b(?:crucial|vital|essential|pivotal|critical|robust|seamless|powerful|comprehensive|cutting-edge|revolutioniz\w*|game.?chang\w*|landscape|testament|delve|key (?:insight|benefit|takeaway|point|factor|advantage|difference|challenge|step))\b/i) },
  { id: "tell-vague-number", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "factualGap", description: "A quantity word may need an actionable value or bound.", severity: "MED", confidence: "contextual", profiles: "all", action: "Check whether a value is needed; ask the author for any missing quantity or condition and leave the source untouched.", autofix: "never", detect: phrase(/\b(?:quickly|slowly|significantly|substantially|dramatically)\b/i) },
  { id: "tell-weasel", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "factualGap", description: "An attribution phrase may need a named source.", severity: "MED", confidence: "contextual", profiles: "all", action: "Check surrounding citations; ask for a missing source without inventing one or changing the claim.", autofix: "never", detect: phrase(/\b(?:studies show|research suggests|experts (?:say|agree)|it is (?:widely )?(?:known|believed|understood)|generally considered|some argue)\b/i) },
  { id: "tell-history", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "Historical phrasing can read as changelog material rather than current documentation.", severity: "LOW", confidence: "contextual", profiles: ["generic", "readme", "runbook", "cutover", "spec", "design", "api-reference", "migration", "security", "risk-assessment"], action: "Describe the current behavior, unless the history explains an active decision.", autofix: "review", detect: phrase(/\b(?:previously|used to|no longer|now (?:does|uses|reads|returns)|we (?:removed|changed|renamed)|has been (?:updated|changed|moved))\b/i) },
  { id: "tell-hedge", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "A hedge may obscure the intended claim.", severity: "LOW", confidence: "contextual", profiles: ["generic", "pr", "readme", "adr", "spec", "design", "api-reference"], action: "Keep uncertainty when it is material; otherwise state the condition precisely.", autofix: "review", detect: phrase(/\b(?:it's worth noting|it should be noted|arguably|somewhat|fairly|relatively|might potentially|could possibly|in general|typically)\b/i) },
  { id: "tell-filler", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "A phrase may add no meaning.", severity: "LOW", confidence: "contextual", profiles: "all", action: "Remove the phrase if the sentence means the same thing without it.", autofix: "review", detect: phrase(/\b(?:in order to|due to the fact that|at this point in time|it is important to|when it comes to|in today's|in the world of)\b/i) },
  { id: "tell-emdash", detection: "At least two prose em dashes exceed the configured words-per-occurrence density.", category: "stylistic", description: "Em dashes are dense relative to document prose.", severity: "LOW", confidence: "contextual", profiles: "all", action: "Use sentence structure or punctuation that makes the relationship explicit.", autofix: "review" },
  { id: "tell-conclusion", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "A conclusion signpost may repeat the surrounding content.", severity: "LOW", confidence: "contextual", profiles: "all", action: "Keep the conclusion only if it adds a decision or next action.", autofix: "review", detect: phrase(/\b(?:in conclusion|to sum up|ultimately|at the end of the day)\b|\boverall,/i) },
  { id: "tell-signpost", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "A navigation phrase may be redundant.", severity: "LOW", confidence: "contextual", profiles: "all", action: "Use a descriptive heading or state the content directly.", autofix: "review", detect: phrase(/\b(?:in this section|as mentioned above|let's dive in|we will cover)\b/i) },
  { id: "tell-curly", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "Curly quotation marks conflict with the configured house style.", severity: "LOW", confidence: "contextual", profiles: "all", action: "Use straight quotes if the repository house style requires them.", autofix: "safe", detect: phrase(/[‘’“”]/) },
  { id: "link-here", detection: "Match the prose pattern outside protected content and accepted terminology; interpretation requires context.", category: "stylistic", description: "Link text does not identify its destination.", severity: "LOW", confidence: "contextual", profiles: "all", action: "Use link text that names the linked document or action.", autofix: "review", detect: phrase(/\[(?:here|this|this doc|link|read more|click here)\]\(/i) },
]

export const RULE_BY_ID = new Map(RULES.map((rule) => [rule.id, rule]))
